# Generated by Django 5.1 on 2024-08-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок объявления', max_length=200, verbose_name='название товара')),
                ('price', models.IntegerField(blank=True, help_text='Стоимость товара', null=True, verbose_name='цена товара')),
                ('description', models.TextField(blank=True, help_text='Подробное описание товара', null=True, verbose_name='описание товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания объявления', verbose_name='дата создания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст комментария', verbose_name='текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания комментария', verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
